In [51]:
import pandas as pd
df = pd.read_csv('./과제물/ThoraricSurgery.csv',header= None)

df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,293,1,3.80,2.80,0,0,0,0,0,0,12,0,0,0,1,0,62,0
1,1,2,2.88,2.16,1,0,0,0,1,1,14,0,0,0,1,0,60,0
2,8,2,3.19,2.50,1,0,0,0,1,0,11,0,0,1,1,0,66,1
3,14,2,3.98,3.06,2,0,0,0,1,1,14,0,0,0,1,0,80,1
4,17,2,2.21,1.88,0,0,1,0,0,0,12,0,0,0,1,0,56,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465,98,6,3.04,2.40,2,0,0,0,1,0,11,0,0,0,1,0,76,0
466,369,6,3.88,2.72,1,0,0,0,1,0,12,0,0,0,1,0,77,0
467,406,6,5.36,3.96,1,0,0,0,1,0,12,0,0,0,0,0,62,0
468,25,8,4.32,3.20,0,0,0,0,0,0,11,0,0,0,0,0,58,1
469,447,8,5.20,4.10,0,0,0,0,0,0,12,0,0,0,0,0,49,0

In [52]:
data_set = df.values
X= data_set[:,:17]
y_cls = data_set [:,17]

In [53]:
from sklearn.preprocessing import LabelEncoder

In [54]:
e = LabelEncoder()
e.fit(y_cls)
y = e.transform(y_cls)

In [55]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
import numpy as np

X_tensor = torch.tensor(X.astype(float)).float()
y_tensor = torch.tensor(y.astype(np.int64))

In [67]:
model = nn.Sequential(
    nn.Linear(17,68),
    nn.ReLU(),
    nn.Linear(68,34),
    nn.ReLU(),
    nn.Linear(34,3),
    #nn.Sigmoid()
)

In [68]:
loss_func = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [69]:
#loss_list = []
#output=[i[0]for i in output]

for i in range(3000) : #시간상 100 원래 3000
    optimizer.zero_grad()
    output = model(X_tensor)
    #output = output.view([470])
    #output = netD(real_cpu).view(-1)
    #output = output.type(torch.FloatTensor)
    loss = loss_func(output, y_tensor)
    loss.backward()
    optimizer.step()
    if i%100 == 0 : #시간상 5개 원래 100
        print(loss.item())
       # loss_list.append(loss.item())

1.0695984363555908
0.4162825047969818
0.40621787309646606
0.3938744068145752
0.3788833022117615
0.3631093502044678
0.34960779547691345
0.3371392488479614
0.32300055027008057
0.3088502287864685
0.29938849806785583
0.28437063097953796
0.27644217014312744
0.2683967053890228
0.26278525590896606
0.2639893591403961
0.2527962028980255
0.24982982873916626
0.25513964891433716
0.24414430558681488
0.240022674202919
0.23868484795093536
0.2392343431711197
0.23515334725379944
0.23217514157295227
0.23850944638252258
0.2288450300693512
0.22884023189544678
0.23124775290489197
0.22416429221630096

In [70]:
output = model(X_tensor)

In [71]:
pred= torch.argmax(output, dim=1)
pred_np = pred.detach().numpy()
accu = np.mean(pred_np==y)
print(accu)

0.925531914893617

In [72]:
sm = nn.Softmax(dim=1)
prob=sm(output)

In [73]:
torch.save(model,'model3_2019020494.pth')